app:
  test: 111
  telegramToken: ${TELEGRAM_TOKEN}
  scrapperBaseUrl: "http://localhost:8080"

rabbitmq:
  queueName: queueName
  exchangeName: exchangeName

spring:
  application.name: bot
  rabbitmq.listener.simple.default-requeue-rejected: false

springdoc.swagger-ui.path: /swagger-ui

server.port: 8081

management:
  server.port: 8091
  endpoints:
    enabled-by-default: false
    web:
      base-path:
      exposure.include: health, info, prometheus
      path-mapping: {prometheus: metrics}
  endpoint:
    health.enabled: true
    info.enabled: true
    prometheus.enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
