app:
  test: 111
  scheduler.interval: PT5S

clients:
  github:
    defaultBaseUrl: https://api.github.com
    defaultHeaders:
      Accept: application/vnd.github+json
      X-GitHub-Api-Version: 2022-11-28
  stackoverflow:
    defaultBaseUrl: https://api.stackexchange.com/2.3
    compress: true

spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    driver-class-name: org.postgresql.Driver
    username: scrapper
    password: scrapper

springdoc.swagger-ui.path: /swagger-ui
